language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa

install:
  - sudo apt-get -qq install gcc-4.9
  - sudo apt-get -qq install libgtest-dev
  - GIT_REPOSITORY=$(pwd)
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd $GIT_REPOSITORY

script:
  - mkdir bin
  - cd bin
  - cmake ..
  - cd ..
  - make -Cbin
  - make -Cbin test
