language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libgtest-dev
      - valgrind

install:
  - GIT_REPOSITORY=$(pwd)
  - GTEST_LOCATION=~/gtest
  - mkdir "${GTEST_LOCATION}"
  - cd "${GTEST_LOCATION}"
  - cp -r "${GTEST_LOCATION}/*" ./
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - cd "${GIT_REPOSITORY}"

script:
  - mkdir bin
  - cd bin
  - cmake ..
  - cd ..
  - make -Cbin
  - make -Cbin test
