language: cpp
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libgtest-dev
      - valgrind

install:
  - GIT_REPOSITORY=$(pwd)
  - LIBGTESTDEV_LOCATION=/usr/src/gtest
  - GTEST_COMPILE_LOCATION=~/gtest
  - mkdir -p "${GTEST_COMPILE_LOCATION}"
  - cd "${GTEST_COMPILE_LOCATION}"
  - cp -r "${LIBGTESTDEV_LOCATION}"/* ./
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - cd "${GIT_REPOSITORY}"

script:
  - mkdir bin
  - cd bin
  - cmake -DCMAKE_LIBRARY_PATH="${GTEST_COMPILE_LOCATION}" ..
  - cd ..
  - make -Cbin
  - make -Cbin test
